Repository jayadevvasudevan/Competitive-Programming, pull requests merged in 2020-10, with the labels that each got.

#3 Revert "Create readme.md"
  Python/readme.md
Labels: hacktoberfest 2020

#4 Revert "Revert "Create readme.md""
  Python/readme.md
Labels: hacktoberfest-accepted

#5 new problem added bro
  Python/problem1.md
  Python/solution.md
Labels: hacktoberfest 2020, hacktoberfest-accepted

#6 Create arithmetic sequence.md
  Python/problems/arithmetic sequence.md
Labels: hacktoberfest 2020, hacktoberfest-accepted

#7 New program : Longest palindrome
  Python/problems/longest palindrome.md
Labels: hacktoberfest 2020, hacktoberfest-accepted

#8 Happy number program
  Python/problems/happy number.md
Labels: hacktoberfest 2020, hacktoberfest-accepted

#10 Create Pallindrome.md
  Python/problems/Pallindrome.md
Labels: hacktoberfest 2020, hacktoberfest-accepted

#11 Added Largest number program
  Python/problems/largest_number.md
Labels: hacktoberfest 2020, hacktoberfest-accepted

#12 Create Monotonic Array or not
  Monotonic Array or not
Labels: hacktoberfest 2020, hacktoberfest-accepted
